package com.yantianpeng.mapper;

import com.yantianpeng.entity.User0Entity;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface User0EntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user0
     *
     * @mbg.generated Tue Oct 30 16:38:00 CST 2018
     */
    @Delete({
        "delete from user0",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user0
     *
     * @mbg.generated Tue Oct 30 16:38:00 CST 2018
     */
    @Insert({
        "insert into user0 (id, name, ",
        "pwd)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{pwd,jdbcType=VARCHAR})"
    })
    int insert(User0Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user0
     *
     * @mbg.generated Tue Oct 30 16:38:00 CST 2018
     */
    @Select({
        "select",
        "id, name, pwd",
        "from user0",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="pwd", property="pwd", jdbcType=JdbcType.VARCHAR)
    })
    User0Entity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user0
     *
     * @mbg.generated Tue Oct 30 16:38:00 CST 2018
     */
    @Select({
        "select",
        "id, name, pwd",
        "from user0"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="pwd", property="pwd", jdbcType=JdbcType.VARCHAR)
    })
    List<User0Entity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user0
     *
     * @mbg.generated Tue Oct 30 16:38:00 CST 2018
     */
    @Update({
        "update user0",
        "set name = #{name,jdbcType=VARCHAR},",
          "pwd = #{pwd,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(User0Entity record);
}