package com.yantianpeng.entity;

public class User1Entity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.id
     *
     * @mbg.generated Tue Oct 30 16:38:00 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.name
     *
     * @mbg.generated Tue Oct 30 16:38:00 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.pwd
     *
     * @mbg.generated Tue Oct 30 16:38:00 CST 2018
     */
    private String pwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.id
     *
     * @return the value of user1.id
     *
     * @mbg.generated Tue Oct 30 16:38:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.id
     *
     * @param id the value for user1.id
     *
     * @mbg.generated Tue Oct 30 16:38:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.name
     *
     * @return the value of user1.name
     *
     * @mbg.generated Tue Oct 30 16:38:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.name
     *
     * @param name the value for user1.name
     *
     * @mbg.generated Tue Oct 30 16:38:00 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.pwd
     *
     * @return the value of user1.pwd
     *
     * @mbg.generated Tue Oct 30 16:38:00 CST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.pwd
     *
     * @param pwd the value for user1.pwd
     *
     * @mbg.generated Tue Oct 30 16:38:00 CST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
}